### ISSUE TITLE
Preview query results in the SPARQL DATA CONNECTOR properties window

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#280] opened 2022-05-16 15:05 UTC
Preview the results of SPARQL queries in the properties window of the data connector so the user can instantly confirm they are connecting to and loading the correct data source.

**Comment by nosnickid** [comment] 2022-05-24 08:47
Duplicate of #267

**Closed by nosnickid** 2022-05-24 08:47 UTC
