### ISSUE TITLE
Site Rendering Optimisations

### ISSUE THREAD

**Issue by anojperera** [GSS-Cogs/dd-cms#638] opened 2022-09-21 14:10 UTC
Spike to understand how we can enhance loading and rendering of content in the CMS

**Comment by charlesons** [comment] 2022-10-04 19:00
Current lighthouse scores are as follows:

**Landing page:**
![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/ec373233-9858-4c75-94da-87e5a1a6427d)

**Comment by charlesons** [comment] 2022-10-04 19:01
**Cookies page:**

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/3a773a76-d4d6-45a4-94bf-14cc009acf19)

**Comment by charlesons** [comment] 2022-10-04 19:02
**Climate and weather dashboard:**

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/d159a043-6d29-416c-926b-97ccf0d6dfa5)

**Comment by charlesons** [comment] 2022-10-04 19:02
**The UK's climate is changing article:**

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/3a441f5c-5bb6-4682-afd5-25a18a94e5db)

**Comment by charlesons** [comment] 2022-10-04 19:03
**Articles landing page:**

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/ca86ca47-a56f-4fd5-9df8-734ecc87810c)

**Comment by charlesons** [comment] 2022-10-10 22:35
The network requests for the article The UK's climate is changing article are shown below:

Notable in the waterfall trace is that much of the overall time is spent waiting for a response from the server (the traces in green on the right).

![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/e594feaf-22f6-4e77-a439-926fb1a93a61)

**Comment by charlesons** [comment] 2022-10-10 22:54
![image.png](https://images.zenhubusercontent.com/620cff0fdd7f2f34ac2acfd3/b642354a-113a-417e-a87e-451234690427)

**Comment by charlesons** [comment] 2022-10-10 23:22
Following on from the observation above that more requests raises the likelihood of requests being stalled until a TCP connection becomes available we then looked into what the sources of multiple requests.

One known issue is the double requests for each figure block item which is addressed in issue #612

Setting the duplicate calls aside, there are still a significant number of requests for figure block content in pages which have multiple figures embedded in them. Each piece of embedded content (in this case the figures) require an API call to be made to request that content.

We carried out a simple experiment whereby we created charts inline within a page and compared to a similar sized dashboard page (Climate and Weather) from the CC v2 portal which has embedded figure blocks for each chart.

The inline charts page made a single, slightly larger request to get the whole content of the page, including all of the charts), whereas the embedded figures dashboard page made one request for each figure.

[Uploading... Screencast from 11-10-22 00:04:22.webm]
[Uploading... Screencast from 11-10-22 00:07:25.webm]

**Comment by charlesons** [comment] 2022-10-10 23:36
Based on the above analysis we (@anojperera, @mikeAdamss, @eldeal, @StRhys and @charlesons) have discussed a plan of action to improve and optimise the site rendering:

1. Further explore the causes of long server response times by:
- employing logging
- experimenting with caching in NGINX or Volto
- experimenting with higher resources for the pods in the cluster (potentially a RAM issue?)
2. Keep in mind the possibility of creating an option for inline figure blocks that would result in a single request for all charts on a given page.
3. Highlight best practice to content creators of not adding too many charts and maps to a single page.
4. Further explore possibilities for Server Side Rendering.

**Closed** 2022-10-11 22:59 UTC
Labels: spike, Must Have
